/**
 * Created by David Maser on 12/05/2017.
 */
const calFomat = {
    days:{
        en:{
            0:{
                short:'sun',
                label:'Sunday'
            },
            1:{
                short:'mon',
                label:'Monday'
            },
            2:{
                short:'tue',
                label:'Tuesday'
            },
            3:{
                short:'wed',
                label:'Wednesday'
            },
            4:{
                short:'thu',
                label:'Thursday'
            },
            5:{
                short:'fri',
                label:'Friday'
            },
            6:{
                short:'sat',
                label:'Saturday'
            }
        }
    },
    months:{
        1:{
            en:{
                short:'jan',
                label:'January'
            },
            days:31,
            events:{
                name:'New Years',
                day:1
            }
        },
        2:{
            en:{
                short:'feb',
                label:'February'
            },
            days:28
        },
        3:{
            en:{
                short:'mar',
                label:'March'
            },
            days:31
        },
        4:{
            en:{
                short:'apr',
                label:'April'
            },
            days:30
        },
        5:{
            en:{
                short:'may',
                label:'May'
            },
            days:31
        },
        6:{
            en:{
                short:'jun',
                label:'June'
            },
            days:30
        },
        7:{
            en:{
                short:'jul',
                label:'July'
            },
            days:31
        },
        8:{
            en:{
                short:'aug',
                label:'August'
            },
            days:31
        },
        9:{
            en:{
                short:'sep',
                label:'September'
            },
            days:30
        },
        10:{
            en:{
                short:'oct',
                label:'October'
            },
            days:31
        },
        11:{
            en:{
                short:'nov',
                label:'November'
            },
            days:30
        },
        12:{
            en:{
                short:'dec',
                label:'December'
            },
            days:30,
            events:{
                name:{
                    en:'Christmas',
                    fr:'Noel'
                },
                day:25
            }
        }
    },
    start:'sun',
    show:7
};