/**
 * Created by David Maser on 12/05/2017.
 */
const calFomat = {
    days:{
        en:{
            0:{
                short:'sun',
                label:'Sunday'
            },
            1:{
                short:'mon',
                label:'Monday'
            },
            2:{
                short:'tue',
                label:'Tuesday'
            },
            3:{
                short:'wed',
                label:'Wednesday'
            },
            4:{
                short:'thu',
                label:'Thursday'
            },
            5:{
                short:'fri',
                label:'Friday'
            },
            6:{
                short:'sat',
                label:'Saturday'
            }
        }
    },
    months:{
        en:{
            jan:{
                label:'January',
                days:31,
                events:{
                    name:'New Years',
                    day:1
                }
            },
            feb:{
                label:'February',
                days:28
            },
            mar:{
                label:'March',
                days:31
            },
            apr:{
                label:'April',
                days:30
            },
            may:{
                label:'Mai',
                days:31
            },
            jun:{
                label:'June',
                days:30
            },
            jul:{
                label:'July',
                days:31
            },
            aug:{
                label:'August',
                days:31
            },
            sep:{
                label:'September',
                days:30
            },
            oct:{
                label:'October',
                days:31
            },
            nov:{
                label:'November',
                days:30
            },
            dec:{
                label:'December',
                days:30,
                events:{
                    name:'Christmas',
                    day:25
                }
            }
        }
    },
    start:'sun',
    show:7
};